/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

const { faker } = require("@faker-js/faker");
const constants = require("../../const/constants");

exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex(constants.knex.pets).del();
  console.log("Seeding pets table");
  await knex(constants.knex.pets).insert([
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(), // Random dog name
      species: "dog",
      age: faker.number.int({ min: 1, max: 12 }), // Random age between 1 and 12
      price: faker.number.int({ min: 50, max: 500 }), // Random price between 50 and 500
      breed: faker.animal.dog(), // Random dog breed
      gender: "male", // Generates a gender (male or female)
      color: faker.color.human(), // Random human-readable color
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]), // Two random animal image URLs
      size: faker.helpers.arrayElement(["small", "medium", "large"]), // Random size
      vaccineStatus: faker.datatype.boolean(), // Random vaccine status (true or false)
      description: faker.lorem.sentence(), // Random sentence for the description
      available: true, // Default to available
      shelter_id: "590b5762-89ad-11ef-aa19-e8d8d14985cf", // Assuming this matches an existing shelter UUID in your "shelter" table
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.cat(),
      species: "cat",
      age: faker.number.int({ min: 1, max: 15 }),
      price: faker.number.int({ min: 50, max: 400 }),
      breed: faker.animal.cat(),
      gender: "male",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: faker.helpers.arrayElement(["small", "medium", "large"]),
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: false,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "male",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b5762-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b5762-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b5762-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
    {
      id: knex.raw("UUID()"),
      name: faker.animal.dog(),
      species: "dog",
      age: faker.number.int({ min: 1, max: 5 }),
      price: faker.number.int({ min: 30, max: 200 }),
      breed: faker.animal.dog(),
      gender: "female",
      color: faker.color.human(),
      images: JSON.stringify([faker.image.avatar(), faker.image.avatar()]),
      size: "small",
      vaccineStatus: faker.datatype.boolean(),
      description: faker.lorem.sentence(),
      available: true,
      shelter_id: "590b54d8-89ad-11ef-aa19-e8d8d14985cf",
    },
  ]);
};
